### ISSUE TITLE
patch-T.MPQ

### ISSUE THREAD

**Issue by parashorea** [Helias/mod-bg-twinpeaks#2]
The file "[patch-T.MPQ](https://mega.nz/#F!ksFzBSwI!FirOsvqp6cLvo8ShbvX6_Q?Mkt1QapC)" cannot be downloaded.

**Comment by Helias** [comment]
links updated

By the way, in the repository you have all the client-side files, so you can easily create an MPQ file through the mpqeditor OR you can also create a "directory" inside WoW/Data/ called "patch-T.MPQ" and put there all the files that right now are in the client-side directory of this repository, your client will read them anyway
The only difference is that it's a fake MPQ and the files are not compressed, but for development or testing it's good enough

Thanks for reporting the missing link ;-)

P.S. put a star in the repository if you like it, this will increase the visibility
